// LOGIN
export const CHECK_AUTH_STATUS = "CHECK_AUTH_STATUS"
export const POPULATE_STORE = "POPULATE_STORE"
export const ADD_USER_ID = "ADD_USER_ID"

//ITINERARY
export const GET_DESTINATIONS_START = "GET_DESTINATIONS_START"
export const UPDATE_ITINERARY = "UPDATE_ITINERARY"
export const DESTINATION_ADDED = "DESTINATION_ADDED"
export const DESTINATION_REMOVE = "DESTINATION_REMOVE"
export const DESTINATION_VALUE_CHANGED = "DESTINATION_VALUE_CHANGED"

// SETTINGS screen
export const PREFERNECES_VALUE_CHANGED = "PREFERNECES_VALUE_CHANGED"
export const PERSONALDETAILS_VALUE_CHANGED = "PERSONALDETAILS_VALUE_CHANGED"
